apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-34-pagamento
  labels:
    app: restaurant-34-pagamento
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant-34-pagamento
  template:
    metadata:
      labels:
        app: restaurant-34-pagamento
    spec:
      containers:
        - name: restaurant-34-pagamento
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: restaurant-34-pagamento
                  key: DATABASE_URL
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: restaurant-34-pagamento
                  key: DATABASE_NAME
          image: 035133178716.dkr.ecr.us-east-1.amazonaws.com/restaurante-34-pagamento:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "2500m"
              memory: "256Mi"
