apiVersion: v1
kind: Service
metadata:
  labels:
    app: restaurant-34-pagamento
  name: restaurant-34-pagamento
spec:
  ports:
  - nodePort: 31001
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: restaurante34pagamento
  type: NodePort