name: "QA Pipeline"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  qa:
    name: "QA Pipeline"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Configure Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install Deps
        run: npm install

      - name: Execute Tests
        run: npm run test

    - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage/index.html