name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  qa:
    name: "QA Pipeline"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Deps
        uses: actions/setup-node@v4
        with:
          node-version: 20
        run: npm install

      - name: Execute Tests
        run: npm run test